# Generated by Django 4.1.2 on 2022-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_location',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='car_price',
            field=models.IntegerField(default=0),
        ),
    ]
